# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :wb_server do |lb|
    lb.vm.box = "centos-7.1706_v0.2.0"
    lb.vm.network :private_network, ip: "192.168.56.101"
    #wb.vm.network "public_network", bridge: "eth4", ip:"192.168.131.100", netmask: "255.255.255.0"
    lb.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "wb_server" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "haproxy"
      #chef.json = {
      #  "courses" =>
      #   [{"id":"0001", "name" => "Redes de Computadores"},
      #    {"id":"0002", "name" => "Sistemas Operativos"}
      #   ]
      #}
      #chef.json = {"courses": [{"name":"operativos 2"},{"name":"distribuidos"}]}
    end
  end
 end
end
