# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :lb_server do |lb|
    lb.vm.box = "centos-7.1706_v0.2.0"
    lb.vm.network :private_network, ip: "192.168.56.101"
    lb.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "lb_server" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "haproxy"
      chef.json = {
        "web_servers" => [
          {"ip":"192.168.56.102"},
          {"ip":"192.168.56.103"}
         ]
      }
    end
  end
  config.vm.define :wb_server_1 do |wb1|
    wb1.vm.box = "centos-7.1706_v0.2.0"
    wb1.vm.network :private_network, ip: "192.168.56.102"
    wb1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "wb_server_1_a" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "httpd"
      chef.json = {"service_name" => "Service 1-A"}
    end
  end
  config.vm.define :wb_server_2 do |wb2|
    wb2.vm.box = "centos-7.1706_v0.2.0"
    wb2.vm.network :private_network, ip: "192.168.56.103"
    wb2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "wb_server_1_b" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "httpd"
      chef.json = {"service_name" => "Service 1-B"}
    end
  end
end
