driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibusl: 13.2.20

platforms:
- name: centos-7
  driver:
    box: centos_7

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[git_cookbook::default]
    verifier:
      inspec_tests:
        - path: test/integration/default
    attributes:
