# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.define :centos_server do |server|
    server.vm.box = "centos-7.1706_v0.2.0"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_server" ]
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y httpd
      systemctl start  httpd.service
      systemctl enable httpd.service
    SHELL
  end
end
