#!/bin/sh

# Prerequisites:
# 1. Aptly needs to be installed 
# 2. daemon needs to be installed
# 3. Script needs to be executed by root

# This script will launch aptly serve in a mode that will automatically respawn if it
# crashes. Output will be sent to /var/log/aptly/aptly-daemon.log. A PID file will be
# created in the standard location.

start () {
    echo -n "Starting aptly-daemon..."

    # Start daemon
    daemon --command "aptly serve" --respawn --output=/var/log/aptly/aptly.log --name=aptly-daemon --verbose

    RETVAL=$?
    if [ $RETVAL = 0 ]
    then
        echo "done."
    else
        echo "failed. See error code for more information."
    fi
    return $RETVAL
}

stop () {
    # Stop daemon
    echo -n "Stopping aptly-daemon..."

    daemon --stop --name=aptly-daemon --verbose
    RETVAL=$?

    if [ $RETVAL = 0 ]
    then
        echo "Done."
    else
        echo "Failed. See error code for more information."
    fi
    return $RETVAL
}


restart () {
    daemon --restart --name=aptly-daemon --verbose
}


status () {
    # Report on the status of the daemon
    daemon --running --verbose --name=aptly-daemon
    return $?
}


case "$1" in
    start)
        start
    ;;
    status)
        status
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo $"Usage: aptly-daemon {start|status|stop|restart}"
        exit 3
    ;;
esac

exit $RETVAL
